# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dbishop/energy_cost_test/energy_cost_test.cache/wt [current_project]
set_property parent.project_path C:/Users/dbishop/energy_cost_test/energy_cost_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/pc.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/datamemory.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/pcjumper.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/controlTable.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/instructionmemory.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/registerfile.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/vliwsplitter.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/core.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/cpu.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/Lab2/spimemory.v
}
read_verilog -library xil_defaultlib {
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/alu.v
  C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/sources_1/imports/src/multiplexer.v
}
read_xdc C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/constrs_1/imports/Documents/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/dbishop/energy_cost_test/energy_cost_test.srcs/constrs_1/imports/Documents/ZYBO_Master.xdc]

synth_design -top spimemory_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef spimemory_wrapper.dcp
catch { report_utilization -file spimemory_wrapper_utilization_synth.rpt -pb spimemory_wrapper_utilization_synth.pb }
